version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/dockerfiles/airflow.Dockerfile
  env_file: .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
    _AIRFLOW_WWW_USER_USERNAME: admin
    _AIRFLOW_WWW_USER_PASSWORD: admin
    PYTHONPATH: /opt/airflow:/opt/airflow/src
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
    - ./mlruns:/opt/airflow/mlruns
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 5s
      retries: 10
      start_period: 5s
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -lc
      - |
        set -e
        airflow db migrate
        airflow users create \
          --username "$${_AIRFLOW_WWW_USER_USERNAME}" \
          --password "$${_AIRFLOW_WWW_USER_PASSWORD}" \
          --firstname Admin --lastname Admin --role Admin \
          --email admin@example.com
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: ["bash","-lc","airflow webserver"]
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: ["bash","-lc","airflow scheduler"]
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    command: mlflow server --host 0.0.0.0 --port 5001 --backend-store-uri /mlflow --default-artifact-root /mlflow
    volumes:
      - ./mlruns:/mlflow
    ports:
      - "5001:5001"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001
    volumes:
      - ./data:/app/data
      - ./mlruns:/app/mlruns
    ports:
      - "8000:8000"
    depends_on:
      mlflow:
        condition: service_started

volumes:
  postgres-db-volume:
