version: "3.8"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./airflow/dockerfiles/airflow.Dockerfile
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__LOGGING__LOGGING_LEVEL: INFO
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    # MLflow tracking for tasks
    MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ./src:/opt/airflow/src
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres
    - mlflow

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    entrypoint: ""
    command: >
      bash -c "airflow db init &&
      airflow users create --role Admin --username admin --password admin --firstname Admin --lastname User --email admin@example.com"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MODEL_PATH: /mnt/shared/models/model.joblib
    volumes:
      - ./data:/mnt/shared
    ports:
      - "8000:8000"
    depends_on:
      - airflow-webserver

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlruns

volumes:
  pgdata:
